name: weather_android_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  animate_do: ^3.0.2
  smooth_page_indicator: ^1.0.1
  json_annotation: ^4.8.0
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  crypto: ^3.0.2
  flutter_dotenv: ^5.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  location: ^4.4.0
  http: ^0.13.5
  font_awesome_flutter: ^10.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  hive_generator: ^2.0.0
  mobx_codegen: ^2.1.1
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - .env
    
  fonts:
    - family: Nunito-Regular
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
    - family: Nunito-Medium
      fonts:
        - asset: assets/fonts/Nunito-Medium.ttf
    - family: Nunito-Bold
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
    
    - family: Nunito-Light
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
    # TODO - ADD NUNITO, UBUNTU E KARLA
    # - family: Nunito-Regular
      # fonts:
        # - asset: assets/fonts/Nunito-Light.ttf
