name: weather_android_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  animate_do: ^3.0.2
  smooth_page_indicator: ^1.0.1
  orm: ^3.1.4
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/